[server]
  debug_trace = false

[vpc]
  iam_client_id = ""
  iam_client_secret = ""
  vpc_enabled = true
  vpc_volume_type="vpc-share"
  g2_token_exchange_endpoint_url = "https://iam.bluemix.net"
  g2_riaas_endpoint_url = "https://us-south.iaas.cloud.ibm.com"
  g2_riaas_endpoint_private_url = "https://us-south.iaas.cloud.ibm.com"
  g2_resource_group_id = ""
  g2_api_key = ""
  provider_type = "g2"
  vpc_provider_type = "vpc-share"
  encryption = false
  max_retry_attempt  = 2 # 10 times with exponential re-try with max gap max_retry_gap
  max_retry_gap =  120 # 2 minutes
  api_version = "2021-04-24"   #"2019-07-02"
  vpc_api_generation = 2
  vpc_api_timeout = "120s"

[API]
  PassthroughSecret = ""
