[VPC]
  g2_token_exchange_endpoint_url = "https://iam.stage1.bluemix.net"
  g2_riaas_endpoint_url = "https://us-south-stage01.iaasdev.cloud.ibm.com/"
  g2_riaas_endpoint_private_url = "https://us-south-stage01.iaasdev.cloud.ibm.com"
  g2_resource_group_id = "300b9469ee8676f9a038ecdf408c1a9d"
  g2_api_key = "<api-key>"
  encryption = false
  provider_type = "g2"
  iks_token_exchange_endpoint_private_url = "https://private.containers.test.cloud.ibm.com"

