[server]
  debug_trace = 123

[bluemix]
  iam_url = 123
  iam_client_id = 123
  iam_client_secret = 123
  iam_api_key = 123

[vpc]
  vpc_enabled = 123
  vpc_volume_type=112
  encryption = 12
  vpc_api_timeout = "120s"
  max_retry_attempt  = 10 # 10 times with exponential re-try with max gap max_retry_gap
  max_retry_gap =  -120 # 2 minutes
  api_version = "2019-07-02"
  vpc_api_generation = 1dsadsad